apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-api-deployment
  labels:
    app: price-api
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: price-api
  template:
    metadata:
      labels:
        app: price-api
    spec:
      containers:
      - name: price-api

        image: us-central1-docker.pkg.dev/project-378f1530-eea8-4d9e-80f/price-monitor-repo/price-api:v2.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:

        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_HOST
        - name: DATABASE_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_USER
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DATABASE_NAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres_password
